version: '3' # 版本号
services: # docker容器
  nginx: # 容器名称
    image: nginx:latest # 镜像名:版本号
    restart: always # 设置为always，表明此容器应该在停止的情况下总是重启
    container_name: nginx # 容器名称
    ports: # 本地端口号与容器内部端口号
      - 9002:80
    volumes: # 指定挂载目录，数据卷，将容器中的文件与服务器映射
      - /Users/hongzhao/demo/design-mode/nginx/html:/usr/share/nginx/html
      - /Users/hongzhao/demo/design-mode/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /Users/hongzhao/demo/design-mode/nginx/conf.d:/etc/nginx/conf.d
      - /Users/hongzhao/demo/design-mode/nginx/log:/var/log/nginx
# docker-compose -v # 查看版本
# docker-compose up -d # 启动服务
# docker ps -a | grep nginx
# docker-compose down # 停止服务
# docker-compose logs -f --tail 1000 nginx # 此命令的意思就是查看容器日志，守护线程查看展示1000条。
